### ISSUE TITLE
FINN test in MPAS

### ISSUE THREAD

**Issue by AndrewJConley** [NCAR/IPT#14]
FINN tool is ready to be tested against MPAS grid

**Comment by marybarthbrock** [comment]
The emissions preprocessor tool for FINN was tested by Laura Fowler (MMM; laura@ucar.edu). It works fine with coarse grid MPAS (i.e. fewer grid points) but will be slow when MPAS is at fine resolution (i.e. millions of grid points). We need a solution, such as develop grid weighting in initialization or preprocessed and then assign emissions later. We should have a conversation with Laura and other emissions people (Becky Schwantes, Forrest Lacey) to clarify and find a pathway forward.

**Comment by AndrewJConley** [comment]
Do we have a test grid to work with? @marybarthbrock

**Comment by AndrewJConley** [comment]
This issue seems to be either irrelevant or no longer needed by the group.  I'm closing it.  If someone needs to reopen it, please do so
