### ISSUE TITLE
emission fractionfor CH3CN

### ISSUE THREAD

**Issue by zyqzxn** [NCAR/IPT#38]
In the "rename_and_convert_cmip_hist.ncl" script under "Emissions/CMIP/", when matching the CH3CN from CEDS, it wrote:

"    if ( nspc.eq.30 ) then
     spc_name = "CH3CN"
      spec_ceds  = (/"CO"/)
      spec_bb= (/"NMVOC-HCN"/)
      mw = 41.
      **sf = 0.002; "**

The "sf' should be "0.001" since it was 0.002*CO-em-SOILID-BIOFUEL-anthro, and assuming the SOLID BIOFUEL accounts for half of total CO anthropogenic emissions.

**Comment by lkemmons** [comment]
Thank you for noticing this.  The anthropogenic emissions of CH3CN are very uncertain (and CH3CN has little impact on the chemistry), but it is good to be consistent.

**Comment by AndrewJConley** [comment]
@lkemmons @tilmes. It looks as if this issue has been solved by the latest commit to the master branch.  Please reopen this issue if it still needs to be addressed.
